SecondHand/views.py
# -*- coding: utf-8 -*-
"""
    flaskbb.plugins.SecondHand.views
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    This module contains the SecondHand view.

"""
import json
import os
from flask_allows import Permission
from flask import Blueprint, current_app, request, redirect, url_for
from flask_login import current_user, login_fresh
from flaskbb.utils.requirements import IsAdmin
from flaskbb.utils.helpers import render_template, FlashAndRedirect
from flaskbb.user.models import User, Guest
import SecondHand
import datetime
from .form import ReleaseItemsForm, PurchaseItemsForm, ChangeItemsForm
from conversations.models import Conversation, Message
import uuid
from .model import Items, Items_del
from .helper import upload_item_picture, no_right, exception_process, check_seller_existing
from flask_wtf.file import FileStorage

SecondHand_bp = Blueprint("SecondHand_bp", __name__, template_folder="templates", static_folder="static")


@SecondHand_bp.before_request
def check_before_request():
    """Checks if the login is fresh for the current user, otherwise the user
            has to reauthenticate."""
    if not login_fresh():
        return current_app.login_manager.needs_refresh()
    if isinstance(current_user, Guest) or current_user.primary_group.banned:
        f_r = FlashAndRedirect(
            message="您被禁止访问SecondHand平台，请联系论坛管理团队",
            level="danger",
            endpoint="forum.index"
        )
        return f_r()


@SecondHand_bp.route("/", methods=['GET', 'POST'])
@exception_process
def SecondHand_index():
    session = SecondHand.Session()
    items = session.query(Items).filter(Items.orderStatusId == 1).all()
    items = filter(check_seller_existing, items)
    user_id = current_user.id
    form = ReleaseItemsForm()
    if request.method == 'GET':
        return render_template(
            "SecondHand_index.html",
            items=items,
            handler_url=url_for("SecondHand_bp.SecondHand_index"),
            form=form
        )
    if form.validate_on_submit():
        path = os.path.join(os.path.dirname(__file__), "static/upload_file/image/item_main_picture")
        file_path = upload_item_picture(
            path,
            form.main_picture.data,
            current_user.id,
            form.items_name.data)
        item = Items(items_name=form.items_name.data,
                     price=float(form.price.data),
                     sellerID=user_id,
                     description=form.desc.data,
                     main_picture_url=file_path,
                     post_date=datetime.datetime.now(),
                     orderStatusId=1)
        session = SecondHand.Session()
        session.add(item)
        session.commit()
        return json.dumps({"validate": "success"})
    else:
        error = dict({"validate": "error"}, **form.errors)
        print(error)
        return json.dumps(error)


@SecondHand_bp.route("/userRecord")
@exception_process
def SecondHand_userRecord():
    session = SecondHand.Session()
    onSalse = session.query(Items).filter(Items.sellerID == current_user.id, Items.orderStatusId == 1).all()
    onTransaction = session.query(Items).filter(Items.sellerID == current_user.id,
                                                Items.orderStatusId.in_([2, 3, 5])).all()
    success = session.query(Items).filter(Items.sellerID == current_user.id, Items.orderStatusId.in_([4, 6])).all()
    buyer_onTransaction = session.query(Items).filter(Items.buyerID == current_user.id,
                                                      Items.orderStatusId.in_([2, 3, 5])).all()
    buyer_success = session.query(Items).filter(Items.buyerID == current_user.id, Items.orderStatusId.in_([4, 6])).all()
    tabTarget = request.args.get("tabTarget")
    form_change = ChangeItemsForm()
    return render_template(
        "SecondHand_userRecord.html",
        myRelease=onSalse,
        user=current_user,
        onTransaction=onTransaction,
        success=success,
        buyer_onTransaction=buyer_onTransaction,
        buyer_success=buyer_success,
        tabTarget=tabTarget,
        form_change=form_change,
        id=id,  # It is a function
        User=User  # it is a class
    )


@SecondHand_bp.route("/SecondHand_desc/<item>", methods=['GET', 'POST'])
@exception_process
def SecondHand_desc(item):
    session = SecondHand.Session()
    i: Items = session.query(Items).filter(Items.id == item).one()
    user = User.query.filter(i.sellerID == User.id).one()
    form = PurchaseItemsForm()
    form_change = ChangeItemsForm()
    if request.method == 'GET':
        return render_template(
            "SecondHand_itemsDesc.html",
            item=i,
            user=user,
            request=request,
            form=form,
            form_change=form_change,
            User=User  # It is Model of user
        )
    if form.validate_on_submit():
        i.buyerID = current_user.id
        i.start_transaction_date = datetime.datetime.now()
        i.orderStatusId = 2
        i.buyer_phone = form.phone.data
        i.buyer_email = form.email.data
        i.buyer_location = form.location.data
        i.buyer_comment = form.comment.data
        session.commit()
        # send message to seller
        purchase_message = "系统自动发送\n{} 已下单 {} 商品\n&#128230;买方的联系方式:\n手机: {}\nEmail: {}\n地址: {}\n留言: {}" \
            .format(current_user.username, i.items_name, form.phone.data, form.email.data, form.location.data,
                    form.comment.data)
        message_seller = Message(
            message=purchase_message,
            user_id=current_user.id
        )
        conversation_seller = Conversation(
            subject=current_user.username + " 已下单 " + i.items_name,
            draft=False,
            shared_id=uuid.uuid4(),
            from_user_id=current_user.id,
            to_user_id=i.sellerID,
            user_id=i.sellerID,
            unread=True,
        )
        conversation_seller.save(message=message_seller)
        message_buyer = Message(
            message=purchase_message,
            user_id=current_user.id
        )
        conversation_buyer = Conversation(
            subject=current_user.username + " 已下单 " + i.items_name,
            draft=False,
            shared_id=uuid.uuid4(),
            from_user_id=current_user.id,
            to_user_id=i.sellerID,
            user_id=current_user.id,
            unread=False,
        )
        conversation_buyer.save(message=message_buyer)
        return json.dumps({"validate": "success"})
    else:
        error = dict({"validate": "error"}, **form.errors)
        print(error)
        return json.dumps(error)


# -----------------------------------
#   change items or del
# -----------------------------------

@SecondHand_bp.route("/del_myRelease/<item>")
@exception_process
def SecondHand_del_myRelease(item):
    session = SecondHand.Session()
    i: Items = session.query(Items).filter(Items.id == item).one()
    url = request.args.get("next_url")
    if i.orderStatusId in [6, 4] and current_user.id == i.sellerID:
        i.sellerID = None
        session.commit()
        return redirect(url)
    elif i.orderStatusId in [6, 4] and current_user.id == i.buyerID:
        i.buyerID = None
        session.commit()
        return redirect(url)
    elif (i.orderStatusId == 1 and current_user.id == i.sellerID) or Permission(IsAdmin, identity=current_user):
        item_del = Items_del(
            prev_id=i.id,
            items_name=i.items_name,
            price=i.price,
            sellerID=i.sellerID,
            buyerID=i.buyerID,
            post_date=i.post_date,
            start_transaction_date=i.start_transaction_date,
            success_transaction_date=i.success_transaction_date,
            main_picture_url=i.main_picture_url,
            description=i.description,
            orderStatusId=i.orderStatusId,
            buyer_phone=i.buyer_phone,
            buyer_email=i.buyer_email,
            buyer_location=i.buyer_location,
            buyer_comment=i.buyer_comment,
            del_date=datetime.datetime.now())
        session.add(item_del)
        session.delete(i)
        session.commit()
        return redirect(url)
    else:
        return no_right()


@SecondHand_bp.route("/buyer_success/<item>")
@exception_process
def SecondHand_buyer_success(item):
    session = SecondHand.Session()
    i: Items = session.query(Items).filter(Items.id == item).one()
    if current_user.id == i.buyerID:
        i.orderStatusId = 3
        session.commit()
        url = request.args.get("next_url")
        return redirect(url)
    else:
        session.close()
        return no_right()


@SecondHand_bp.route("/seller_success/<item>")
@exception_process
def SecondHand_seller_success(item):
    session = SecondHand.Session()
    i: Items = session.query(Items).filter(Items.id == item).one()
    if current_user.id == i.sellerID:
        i.orderStatusId = 4
        i.success_transaction_date = datetime.datetime.now()
        session.commit()
    url = request.args.get("next_url")
    return redirect(url)


@SecondHand_bp.route("/buyer_cancel/<item>")
@exception_process
def SecondHand_buyer_cancel(item):
    session = SecondHand.Session()
    i: Items = session.query(Items).filter(Items.id == item).one()
    i.orderStatusId = 5
    session.commit()
    # send message to seller
    purchase_message = "系统自动发送\n&#10071;{} 已取消购买 {} 商品\n请尽快与买家联系，如有争议请联系论坛管理团队" \
        .format(current_user.username, i.items_name)
    message_seller = Message(
        message=purchase_message,
        user_id=current_user.id
    )
    conversation_seller = Conversation(
        subject=current_user.username + " 已取消购买 " + i.items_name,
        draft=False,
        shared_id=uuid.uuid4(),
        from_user_id=current_user.id,
        to_user_id=i.sellerID,
        user_id=i.sellerID,
        unread=True,
    )
    conversation_seller.save(message=message_seller)
    message_buyer = Message(
        message=purchase_message,

SecondHand/templates/SecondHand_index.html
{% extends theme("layout.html") %}
{% set page_title = "讯飞未来港BBS二手交易平台" %}
{% block head_extra %}
    <script src="{{ url_for('SecondHand_bp.static', filename='jquery-3.6.0.min.js') }}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-center text-primary">{{ SecondHand_config["SecondHandName"] }}</h1>
        <div class="container-fluid my-4">
            <div class="d-flex justify-content-end mb-4">
                <button type="button" class="btn btn-secondary btn-lg shadow" data-bs-toggle="modal"
                        data-bs-target="#ReleaseItemsModal">+ 发布物品
                </button>
            </div>
{#            <div class="row justify-content-between align-content-center mb-4 row-cols-4">#}
{#                                <div class="col-12 offset-md-3 col-md-6">#}
{#                                    <div class="input-group mb-3 ">#}
{#                                        <input type="text" class="form-control shadow" placeholder="请输入搜索的内容"#}
{#                                               aria-label="Recipient's username" aria-describedby="button-addon2" style="height: 55px; border-radius: 20px 0 0 20px;">#}
{#                                        <button class="btn btn-outline-secondary shadow" type="button" id="button-addon2" style="width: 55px; border-radius: 0 20px 20px 0;"><span#}
{#                                                class="fas fa-search" ></span></button>#}
{#                                    </div>#}
{#                                </div>#}
{#                <div class="col-12 col-md-3">#}
{##}
{#                </div>#}
{#            </div>#}


            <div class="row row-cols-2 row-cols-lg-4 g-4">
                {% for i in items %}
                    <div class="col">
                        <div class="card">
                            <a href="{{ url_for("SecondHand_bp.SecondHand_desc", item=i.id) }}">

                                {% if i.main_picture_url is none %}
                                    <div class="row align-items-center" style="overflow: hidden; height: 350px;">
                                        <div class="col"><h4 class="text-secondary text-center">无图片</h4></div>
                                    </div>
                                {% else %}
                                    <div class="align-items-center" style="overflow: hidden; height: 350px;">
                                        <img src="{{ url_for("SecondHand_bp.static", filename=i.main_picture_url) }}"
                                             class="img-thumbnail"/>
                                    </div>
                                {% endif %}

                                <div class="card-body">
                                    <h5 class="card-title">{{ i.items_name }}</h5>
                                    <p class="card-text">¥{{ i.price }}</p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-lg justify-content-center m-5">
                    <li class="page-item disabled">
                        <a class="page-link">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <!--发布商品Model-->
    <div class="modal fade" id="ReleaseItemsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">发布物品</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div id="ReleaseMessage">
                </div>
                <form action="{{ handler_url }}" method="post" id="ReleaseItemsForm">
                    {{ form.csrf_token }}

                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="recipient-name" class="col-form-label">物品名称*</label>
                            {{ form.items_name(class="form-control" ) }}
                        </div>
                        <div class="mb-3">
                            <label for="message-text" class="col-form-label">价格*</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text">¥</span>
                                {{ form.price(class="form-control" ) }}
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="message-text" class="col-form-label">上传图片</label>
                            {{ form.main_picture(class="form-control") }}
                        </div>
                        <div class="mb-3">
                            <label for="message-text" class="col-form-label">描述</label>
                            {{ form.desc(class="form-control" ) }}
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-primary btn-lg" id="releaseButton">发布</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <script>
        var ReleaseItemsModal = document.getElementById('ReleaseItemsModal')
        ReleaseItemsModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            var button = event.relatedTarget
            // Extract info from data-bs-* attributes
            var recipient = button.getAttribute('data-bs-whatever')
        })


        $("#releaseButton").on("click", function (event) {
            event.preventDefault();
            var form = new FormData(document.getElementById("ReleaseItemsForm"));
            $.ajax({
                url: "{{ url_for('SecondHand_bp.SecondHand_index') }}",
                type: "post",
                data: form,
                dataType: 'json',
                processData: false,
                contentType: false,
                success: function (response) {
                    if (response["validate"] === "success") {
                        location.href = {{ url_for("SecondHand_bp.SecondHand_index") }};
                    } else if (response["validate"] === "error") {
                        var html = ""
                        for (var i in response) {
                            if (i !== "validate") {
                                html += `<div class="alert alert-danger d-flex align-items-center m-2 alert-dismissible fade show" role="alert">
                        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                            <use xlink:href="#exclamation-triangle-fill"/>
                        </svg>
                        ${response[i]}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>`

                            }
                        }
                        document.getElementById('ReleaseMessage').innerHTML = html
                    } else {
                        document.getElementById('ReleaseMessage').innerHTML = `<div class="alert alert-danger d-flex align-items-center m-2 alert-dismissible fade show" role="alert">
                        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                            <use xlink:href="#exclamation-triangle-fill"/>
                        </svg>
                        发布失败，请重试！
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>`
                    }
                },
                error: function (response) {
                    document.getElementById('ReleaseMessage').innerHTML = `<div class="alert alert-danger d-flex align-items-center m-2 alert-dismissible fade show" role="alert">
                        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:">
                            <use xlink:href="#exclamation-triangle-fill"/>
                        </svg>
                        发布失败，请重试！
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>`
                }
            })
        })
    </script>

    {% include 'helper/alert_svg.html' %}
{% endblock %}

SecondHand/templates/SecondHand_mgmt.html
{#{% set page_title = title %}#}
{#{% set active = "SecondHand_bp.SecondHand_mgmt" %}#}

{% extends theme("management/management_layout.html") %}

{% block breadcrumb %}
    <ol class="breadcrumb flaskbb-breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('forum.index') }}">{% trans %}Forum{% endtrans %}</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('management.overview') }}">{% trans %}
            Management{% endtrans %}</a></li>
        <li class="breadcrumb-item active">二手交易管理</li>
    </ol>
{% endblock %}

{% block management_content %}
    {%- from theme('_macros/pagination.html') import render_pagination -%}
    {%- from theme('_macros/navigation.html') import navlink with context -%}
    {%- from theme('_macros/form.html') import render_field -%}

    <div class="col-md-3 settings-col">
        <div class="nav-sidebar">
            <ul class="nav">
                {{ navlink('management.forums', _("Manage Forums")) }}
                {{ navlink('management.add_forum', _("Add Forum")) }}
                {{ navlink('management.add_category', _("Add Category")) }}
            </ul>
        </div>
    </div>


    <div class="col settings-col with-left-border">
        <div class="card settings">
            <div class="card-header settings-header">
                <span class="fas fa-hand-holding-usd"></span> 二手交易管理
            </div>
            <div class="card-body settings-body">
                <form class="row p-2" role="form" method="post">

                </form>
            </div>
        </div>
    </div>
{% endblock %}